services:
  postgres:
    image: postgres:16-alpine
    container_name: ideas-postgres
    #restart: unless-stopped
    environment:
      POSTGRES_DB: ideas_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ideas_tracker"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ideas-pgadmin
    #restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ideas.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      #PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    #volumes:
    #  - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  #pgadmin_data:
